### ISSUE TITLE
Overwriting of marker values when audio is playing

### ISSUE THREAD

**Issue by s-platte** [KoALa-MHF/koala-app#278] opened 2023-07-04 16:38 UTC
If you play the piece again after annotations have been done, the slider marker values will be overwritten with those of the last slider position. 

1. Annotate with slider marker
2. Play the piece again
3. Visualizations show that the slider marker values are overwritten by those of the current slider position

Overwriting slider marker values should only be possible when the slider marker button is pressed and moved again. In general, all buttons should be disabled and only when the buttons are pressed values should be recorded.

macOS Ventura 13.3.1 (a)
Chrome 113.0.5672.126
Safari 16.4
Firefox Version 113.0.5672.126
Microsoft Edge Version 114.0.1823.67

**Comment by TS-Daniel16** [comment] 2023-07-16 13:44
@s-platte your definition from the issue is different to what we discussed initially how moving in the audio file should work for sliders. We said back then, that if the position is set to a time in the "future" the values between the last stop and the new start are not recorded for the slider, but that the slider itself is also not reset to its initial position and recording from there on with the set value of the slider. To keep things consistent, we then also said that overwriting values in the past (moving the position to an earlier position in the audio track where already values were recorded) would work that we cut the annotation at the new start position (leaving the old value until the new start position) and deleting all values from there on into the future / end of audio file. To also keep consistency we said that the slider is not reset, but will record with its last value.

If that should behave differently, could you provide a detailed description (what happens to the slider, which value is being recorded, etc.) of the wanted outcome for all above mentioned scenarios here:
1. New set position is greater than the last position
2. New set position is earlier than the last position (what should happen with the already created annotations)
3. New set position is greater than last position, but there were already annotations in between the last and new position (and after that)

**Comment by TS-Daniel16** [comment] 2023-08-07 19:55
We aligned the following behavior:

1. Annotations for a slider marker will only be created as soon as the slider is moved. That applies to all situations where the audio was stopped (start of audio file, pause or stop is pressed, running audio is set to a different position)
2. As soon as annotations are to be split/overwritten, the annotations from the current audio position until the end of the audio file are marked as "potentially deleted or changed" which is displayed in a more transparent way then the overwriting value

**Comment by s-platte** [comment] 2023-08-08 06:44
I prefer the second solution, where the complete annotation becomes transparent while parts of it are overwritten – this could be called "revision mode" and described that way in the documentation. I think this visualization is less confusing than the solution with the gap.

@KoALa-MHF/mh-team What do you think?

**Comment by TS-Daniel16** [comment] 2023-10-17 08:20
@KoALa-MHF/mh-team we agreed on cleaning up the overwritten annotations when the user presses stop or pause. The pause option would in that scenario then mean, that also the last active annotation will be closed with pause. Currently it is implemented, that the last state will be continued if the audio position is not changed. So question is, if you are ok with closing the annotation on pause same as it would be happening with the stop action?

**Comment by TS-Daniel16** [comment] 2023-10-22 10:06
@KoALa-MHF/mh-team and one more question in that context: what should happen when the owner closes their browser/tab or navigates to a different page and the audio is still playing and participants still have open annotations (slider and range). Should the owner be warned, should it be not possible to navigate/close browser while playing the audio? Or something different?

**Comment by TS-Daniel16** [comment] 2023-10-28 20:31
@KoALa-MHF/mh-team friendly reminder for the two questions above

**Comment by TaSpatzHfM** [comment] 2023-10-31 08:55
> @KoALa-MHF/mh-team we agreed on cleaning up the overwritten annotations when the user presses stop or pause. The pause option would in that scenario then mean, that also the last active annotation will be closed with pause. Currently it is implemented, that the last state will be continued if the audio position is not changed. So question is, if you are ok with closing the annotation on pause same as it would be happening with the stop action?

That's sounds good to us to treat pause and stop the same (as stop)

**Comment by TaSpatzHfM** [comment] 2023-10-31 08:57
> @KoALa-MHF/mh-team and one more question in that context: what should happen when the owner closes their browser/tab or navigates to a different page and the audio is still playing and participants still have open annotations (slider and range). Should the owner be warned, should it be not possible to navigate/close browser while playing the audio? Or something different?

The owner should be warned that there are still open annotations and that he stops the ongoing session if he continues

**Closed** 2024-03-18 18:39 UTC
Labels: bug, enhancement
